# Generated by Django 4.1.5 on 2023-01-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                ("description", models.TextField(verbose_name="Описание")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="image/")),
                ("price", models.FloatField(verbose_name="Цена")),
                ("date_org", models.DateField(verbose_name="Дата создания")),
                ("date_fill", models.DateField(verbose_name="Дата заполнения")),
            ],
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты",},
        ),
    ]
